version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    depends_on:
      - pgsql
  pgsql:
    image: postgres:15-alpine3.17
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${PORT_PGSQL:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
volumes:
  db_data:
    driver: local
